#!/bin/bash
set -e

BUILD_PLAN=${BUILD_PLAN:-IosevkaCustom}
VERSION=${VERSION:-v29.2.0}
FORMAT=${FORMAT:-ttf}

mkdir -p Iosevka
cd Iosevka

if [[ -f package.json ]]; then
  git fetch origin tags/$VERSION
  git checkout tags/$VERSION
else
  git clone https://github.com/be5invis/Iosevka . --depth 1 --branch $VERSION
fi

cp ../private-build-plans.toml .

npm install
npm run build -- $FORMAT::$BUILD_PLAN

echo -e "\nBuilt $BUILD_PLAN $(git describe --tags)"

if [[ $FORMAT == 'ttf' ]] && [[ $OSTYPE == 'darwin'* ]]; then
  echo Install by running:
  echo
  echo "    cp Iosevka/dist/$BUILD_PLAN/ttf/*.ttf ~/Library/Fonts/"
  echo
fi
