#!/bin/bash
set -e

# Usage: ./build <plans...>

BUILD_PLANS=${@:-IosevkaCustom IosevkaCustomQuasiProportional}
IOSEVKA_VERSION=${IOSEVKA_VERSION:-v29.2.0}
FORMAT=${FORMAT:-ttf}

mkdir -p Iosevka
cd Iosevka

if [[ -f package.json ]]; then
  git fetch origin tags/$IOSEVKA_VERSION
  git checkout tags/$IOSEVKA_VERSION
else
  git clone https://github.com/be5invis/Iosevka . --depth 1 --branch $IOSEVKA_VERSION
fi

cp ../private-build-plans.toml .

npm install

for plan in $BUILD_PLANS; do
  npm run build -- $FORMAT::$plan
  echo -e "\nBuilt $plan $(git describe --tags)"
done
