[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-custom.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
l = "serifed-flat-tailed"
t = "flat-hook"
u = "toothless-rounded-serifless"
one = "base"
four = "semi-open-non-crossing"
asterisk = "penta-low"
paren = "flat-arc"
ampersand = "upper-open"
bar = "force-upright"
lig-equal-chain = "without-notch"

[buildPlans.iosevka-custom.ligations]
inherits = "default-calt"
disables = ["llgg"]
