on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install -y ttfautohint
      - run: ./build
      - uses: actions/upload-artifact@v7
        with:
          name: IosevkaCustom-ttf
          path: Iosevka/dist/*/TTF/

  release:
    if: github.ref_type == 'tag'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: IosevkaCustom-ttf
          skip-decompress: true
      - uses: softprops/action-gh-release@v2
        with:
          files: IosevkaCustom-ttf.zip
